import React, { useEffect, useState } from "react";

export default [
    <span data-ty="input">ironfish config:show</span>,
    <span data-ty>
    {`
{
   "bootstrapNodes": [
      "test.bn1.ironfish.network"
   ],
   "databaseName": "default",
   "databaseMigrate": false,
   "defaultTransactionExpirationSequenceDelta": 15,
   "editor": "",
   "enableListenP2P": true,
   "enableLogFile": false,
   "enableRpc": true,
   "enableRpcIpc": true,
   "enableRpcTcp": false,
   "enableRpcTls": true,
   "enableSyncing": true,
   "enableTelemetry": true,
   "enableMetrics": true,
   "getFundsApi": "https://api.ironfish.network/faucet_transactions",
   "ipcPath": "/root/.ironfish/ironfish.ipc",
   "logLevel": "*:info",
   "logPeerMessages": false,
   "logPrefix": "[%tag%]",
   "miningForce": false,
   "blockGraffiti": "derek",
   "nodeName": "derek",
   "nodeWorkers": -1,
   "nodeWorkersMax": 6,
   "p2pSimulateLatency": 0,
   "peerPort": 9033,
   "rpcTcpHost": "localhost",
   "rpcTcpPort": 8020,
   "rpcTcpSecure": false,
   "tlsKeyPath": "/Users/derek/.ironfish/certs/node-key.pem",
   "tlsCertPath": "/Users/derek/.ironfish/certs/node-cert.pem",
   "maxPeers": 50,
   "minimumBlockConfirmations": 12,
   "minPeers": 1,
   "targetPeers": 50,
   "telemetryApi": "https://api.ironfish.network/telemetry",
   "accountName": "default",
   "generateNewIdentity": false,
   "blocksPerMessage": 20,
   "minerBatchSize": 25000,
   "poolName": "Iron Fish Pool",
   "poolAccountName": "default",
   "poolBanning": true,
   "poolBalancePercentPayout": 10,
   "poolHost": "0.0.0.0",
   "poolPort": 9034,
   "poolDifficulty": "15000000000",
   "poolAttemptPayoutInterval": 900,
   "poolSuccessfulPayoutInterval": 7200,
   "poolStatusNotificationInterval": 1800,
   "poolRecentShareCutoff": 7200,
   "poolDiscordWebhook": "",
   "poolMaxConnectionsPerIp": 0,
   "poolLarkWebhook": "",
   "jsonLogs": false,
   "explorerBlocksUrl": "https://explorer.ironfish.network/blocks/",
   "explorerTransactionsUrl": "https://explorer.ironfish.network/transaction/"
}
        `}
  </span>,
];
