/* DO NOT EDIT THIS FILE DIRECTLY, INSTEAD LOOK AT update-links.js */
import React from "react"
import styles from "./anchor.module.css"
import { useLocation } from 'react-router-dom';

const Anchor = ({ name, children }) => {
  const scrolledRef = React.useRef(false)
  const { hash } = useLocation()

  React.useEffect(() => {
    if (hash && !scrolledRef.current) {
      const id = hash.replace('#', '');
      const element = document.getElementById(id);

      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
        scrolledRef.current = true;
      }
    }
  }, []);

  return (
    <span className={styles.anchor}>
      {children}
      <a href={`#${name}`} id={name} className={styles.anchorHash}>#</a>
    </span>
  )
}

export default Anchor
