/* DO NOT EDIT THIS FILE DIRECTLY, INSTEAD LOOK AT update-links.js */
import React from 'react'
import clsx from 'clsx'
import styles from './links.module.css'

const links = [
  [
    "Website",
    "https://ironfish.network"
  ],
  [
    "Docs",
    "https://ironfish.network/docs"
  ],
  [
    "Github",
    "https://github.com/iron-fish"
  ],
  [
    "Twitter",
    "https://twitter.com/ironfishcrypto"
  ],
  [
    "Discord",
    "https://discord.gg/ironfish"
  ],
  [
    "Telegram",
    "https://t.me/ironfishcryptochat"
  ]
]

const Link = ({ href, children }) => (
  <a className={clsx(styles.link, "button", "button--outline")} href={href}>
    {children}
  </a>
)

const Links = () => (
  <div className={styles.page}>
    <header className={styles.header}>
      <img src="/img/logo.svg" className={styles.logo}/>
    </header>
    {links.map(([label, link]) => (
      <Link href={link} key={link}>
        {label}
      </Link>
    ))}
    <footer className={styles.footer}>
      <img src="/img/careers/submarine.gif" className={styles.sub} />
    </footer>
  </div>
)

export default Links
