/* DO NOT EDIT THIS FILE DIRECTLY, INSTEAD LOOK AT update-links.js */
import React from "react"
import clsx from "clsx"
import styles from "./links.module.css"

const links = [
  [
    "Website",
    "https://bit.ly/3P7jUH4"
  ],
  [
    "Docs",
    "https://bit.ly/3FQlSYp"
  ],
  [
    "Github",
    "https://bit.ly/3FJcu8Q"
  ],
  [
    "Twitter",
    "https://bit.ly/3w6l91X"
  ],
  [
    "Discord",
    "https://bit.ly/3PebCNS"
  ],
  [
    "Telegram",
    "https://bit.ly/3wosBnO"
  ]
]

const Link = ({ href, children }) => (
  <a className={clsx(styles.link, "button", "button--outline")} href={href}>
    {children}
  </a>
)

const Links = () => (
  <div className={styles.page}>
    <header className={styles.header}>
      <img src="/img/logo.svg" className={styles.logo} />
    </header>
    {links.map(([label, link]) => (
      <Link href={link} key={link}>
        {label}
      </Link>
    ))}
    <footer className={styles.footer}>
      <img src="/img/links/empower.gif" className={styles.sub} />
    </footer>
  </div>
)

export default Links