name: Update Search Index

on:
  push:
    branches:
      - rahul/test-search-index

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: yarn install

    - name: Generate Search Index
      run: yarn gen-search-index

    - name: Set up Git Config
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Skip Duplicate Actions
      id: skip_check
      uses: fkirc/skip-duplicate-actions@v5.3.1
      with:
        cancel_others: 'true'
        concurrent_skipping: 'outdated_runs'

    - name: Extract Branch Name
      id: extract_branch
      shell: bash
      run: |
        echo "::set-output name=branch::${{ github.head_ref }}"

    - name: Commit and Push Search Index Updates
      if: steps.skip_check.outputs.should_skip != 'true'  # Only run if not skipped
      run: |
        git add -A
        git commit -m "Update search index" || echo "No changes to commit"
        git push origin ${{ steps.extract_branch.outputs.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
